### ISSUE TITLE
Open file viewer in IOS 13 is not working

### ISSUE THREAD

**Issue by tuanduc2904** [vinzscam/react-native-file-viewer#64] opened 2019-10-04 02:13 UTC
I am using react-native-file-viewer on my project. It works fine on other devices but on iOS 13 it doesn't work
![Simulator Screen Shot - iPhone X - 2019-10-04 at 09 10 25](https://user-images.githubusercontent.com/30556451/66176232-2e1aea00-e687-11e9-8244-a3625289134c.png)

**Comment by vinzscam** [comment] 2019-10-04 03:02
It looks you have downloaded a non pdf file but you have given ".pdf" as
file's extension. Please save the file with the correct extension. This is
required by iOS.

**Comment by nysamnang** [comment] 2019-10-04 10:07
@vinzscam I don't think so because i had the same issue. It happens on iOS simulator only, after testing on the real device it's ok.
![Simulator Screen Shot - iPhone X - 2019-10-04 at 16 55 39](https://user-images.githubusercontent.com/28054921/66199115-23cd1000-e6c8-11e9-87c2-81e133e9ec26.png)

```
React Native Environment Info:
    System:
      OS: macOS 10.14.6
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
```

I think you should investigate this problem and thank for the awesome package.

**Comment by vinzscam** [comment] 2019-10-04 10:12
Could you please send your snippet code?

Il giorno ven 4 ott 2019 alle ore 12:07 NY Samnang <notifications@github.com>
ha scritto:

**Comment by AlexisAguilera06** [comment] 2019-10-04 16:42
the problem is with the path, try with this solution:

`    DocumentPicker.pick({
      type: [DocumentPicker.types.allFiles]
    }).then((res) => {
      res.uri = res.uri.replace('file://', '');
      console.log('path', res.uri);
      FileViewer.open(res.uri, { showOpenWithDialog: true });
    });
  };`

**Comment by nysamnang** [comment] 2019-10-05 05:54
@vinzscam I think there is nothing wrong.
```
openDocument = async url => {
    const res = await this.props.downloadData(url);
    FileViewer.open(res.path, {
      displayName: "Documents",
      showOpenWithDialog: true,
      showAppsSuggestions: true
    }).catch(() => {
      Alert.alertWithType("warn", "Sorry", "Cannot open file...", 5000);
    });
};
```
`console.log(res.path);`

`"/Users/nysamnang/Library/Developer/CoreSimulator/Devices/64741EC1-XXXX-49BA-XXXX-949A579BDFE3/data/Containers/Data/Application/AA975540-XXXX-41AF-XXXX-FFEC520410A3/Library/Caches/d21ac9a8511fd54e9be18.JPG"`

**Comment by vinzscam** [comment] 2019-10-05 09:31
I can confirm that there is an issue with the iOS 13 Simulator. Based on what I've heard, the issue seems to affect only the simulator. I can't test on a real device right now, but I will do it in the next days.

**Comment by lucasriondel** [comment] 2019-10-05 12:36
@vinzscam could you keep us updated please ?

anyway, i can confirm that it's not working on iOS 13 on a simulator, and i am using [this example](https://github.com/vinzscam/react-native-file-viewer#download-and-open-a-file-using-react-native-fs).

**Comment by tuanduc2904** [comment] 2019-10-07 03:13
> I can confirm that there is an issue with the iOS 13 Simulator. Based on what I've heard, the issue seems to affect only the simulator. I can't test on a real device right now, but I will do it in the next days.

Thank so much

**Comment by vinzscam** [comment] 2019-10-11 09:00
Just an update: I was able to run the library on a iOS 13 device. There are some opened question to Apple regarding this issue, but it's still not clear the reasons why isn't working anymore on the new Simulator.
I will mention the issue in the documentation.

**Comment by ThanhNghia944** [comment] 2019-12-22 11:25
same issue

**Comment by Hassaan68** [comment] 2020-01-02 10:09
> the problem is with the path, try with this solution:
> 
> `DocumentPicker.pick({ type: [DocumentPicker.types.allFiles] }).then((res) => { res.uri = res.uri.replace('file://', ''); FileViewer.open(res.uri, { showOpenWithDialog: true }); }); };`

This solutions has worked for me. the file can be previewed in both ios and android after this solution

**Comment by hnrqsss** [comment] 2020-03-10 18:22
Same here!
iPhone 6s iOs 13

Test on real device and simulator

**Comment by amauryVedana** [comment] 2020-05-06 07:17
Same issue for me on iOS 13, doesn't work on simulator and real device.
Any workaround ? the path does not contains "file://" or anything else, it works fine on ios 12.* simulator and real device. The extension contains .pdf and the file is a pdf.

**Comment by rmanalo-getdevs** [comment] 2020-05-12 14:58
any workaround with this?

**Comment by amauryVedana** [comment] 2020-05-12 15:08
@rmanalo-getdevs if your files doesn't exists too, then this problem is not related to react-native-file-viewer (it can't opens unexisting files).
For us it appears that RNFS.downloadFile had some trouble with the download, we used an other library, and it works.

**Comment by vinzscam** [comment] 2020-05-12 20:20
The issue seems to be fixed on iOS simulators, so I will close this.
If someone else is facing a similar problem, feel free to open a new issue including your snippet, your React Native version and information about the device/simulator you are using.

**Closed by vinzscam** 2020-05-12 20:20 UTC
